### PR TITLE
[PLATFORM-658]: [PrimaOpentelemetryEx] Bump deps

### PR DESCRIPTION
**Pull request by cpiemontese**
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-658

Bump deps & version to prepare for release.

I am unsure if we should bump the minium versions in the `mix.exs` of `teleplug`, `opentelemetry_absinthe` and `opentelemetry_core_deps()`, because I don't think just updating the `mix.lock` will have the desired effect (but I'm not an expert on Elixir deps handling).

### CODE REVIEW

**Comment by LeartS** [comment]
I think we should update the dependencies in the `mix.exs` too, that's what the dependant applications look at I think.

**Comment by cpiemontese** [comment]
Done and update the CHANGELOG accordingly

I assume this can still be considered a patch, am I right?

**Comment by LeartS** [comment]
I think so but I'm no expert/haven't thought much about it.
Worst case if people upgrade their dependency on `prima_opentelemetry_ex` and it breaks something (really unlikely) they can just rollback the dependency upgrade.

**Review by LeartS — APPROVED** [review]

**Comment by cpiemontese** [comment]
Only one way to find out!

**Pull request merged**
