### PR TITLE
[PRIMAUK-3642]: Stonehenge - update for Telepoison updates

### PR DESCRIPTION
**Pull request by michael-a-grammar**
As per the commit, updates the version of Telepoison used

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMAUK-3642

### CODE REVIEW

**Comment by MaeIsBad** [comment]
`~> 1.0.0` already includes 1.0.1, and I don't see a reason to force library users to update if it's not necessary. Updating the mix.lock file in stonehenge to teleplug 1.0.1 should be enough to make all other libraries also use teleplug 1.0.1

https://github.com/primait/stonehenge/blob/c3238c28e09248ed30718c1fd8d0e840c403cee3/mix.lock#L166

**Comment by cpiemontese** [comment]
I agree that libraries shouldn't necessarily bump the minimum version, so I'd leave `~> 1.0` here

Stonehenge can then safely use all the 1.0.1 versions because they are supported by the `~> 1.0` clause

**Comment by michael-a-grammar** [comment]
Sorry chaps - it's the minor version that should have been updated, so `1.1.0` - do this make a difference?

**Comment by cpiemontese** [comment]
I don't think we need to do this, there's no reason to force people to use a `1.1.x` min version

**Pull request closed without merging**
